GAP.Seguros/GAP.Seguros/Controllers/PolizaController.cs
using GAP.Seguros.ModeloDatos;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Formatting;
using System.Web;
using System.Web.Mvc;
//using System.Net.Http.Formatting;

namespace GAP.Seguros.Controllers
{
    public class PolizaController : Controller
    {
        // GET: Poliza
        public ActionResult Index()
        {
            HttpClient clientHttp = new HttpClient();
            clientHttp.BaseAddress = new Uri("https://localhost:44350/");

            var request = clientHttp.GetAsync("api/Poliza").Result;

            if (request.IsSuccessStatusCode)
            {
                var resulstring = request.Content.ReadAsStringAsync().Result;
                var listado = JsonConvert.DeserializeObject<List<Poliza>>(resulstring);
                return View(listado);
            }
            
            return View(new List<Poliza>());

        }

        [HttpGet]
        public ActionResult Nuevo()
        {
            HttpClient clientHttp = new HttpClient();
            clientHttp.BaseAddress = new Uri("https://localhost:44350/");

            var requestTipoPoliza = clientHttp.GetAsync("api/TipoPoliza").Result;

            var requestTipoRiesgo = clientHttp.GetAsync("/api/TipoRiesgo").Result;

            if (requestTipoRiesgo.IsSuccessStatusCode)
            {
                var resulstring = requestTipoRiesgo.Content.ReadAsStringAsync().Result;
                var listadoRiesgo = JsonConvert.DeserializeObject<List<TipoRiesgo>>(resulstring);
                ViewBag.TipoRiesgo = listadoRiesgo;
            }

            if (requestTipoPoliza.IsSuccessStatusCode)
            {
                var resulstring = requestTipoPoliza.Content.ReadAsStringAsync().Result;
                var listadoPoliza = JsonConvert.DeserializeObject<List<TipoPoliza>>(resulstring);
                ViewBag.TipoPoliza = listadoPoliza;
            }
                       

            return View();
        }

        [HttpPost]
        public ActionResult Nuevo(Poliza poliza)
        {
            HttpClient clientHttp = new HttpClient();
            clientHttp.BaseAddress = new Uri("https://localhost:44350/");

            var request = clientHttp.PostAsync("api/Poliza", poliza, new JsonMediaTypeFormatter()).Result;

            if (request.IsSuccessStatusCode)
            {
                var resulstring = request.Content.ReadAsStringAsync().Result;
                var resutado = JsonConvert.DeserializeObject<bool>(resulstring);
                if (resutado)
                {
                    return RedirectToAction("Index");
                }
                return View(poliza);
           
            }
         
            return View(poliza);
        }


        [HttpGet]
        public ActionResult Actualizar(int IdPoliza, string idTipoPolizSelec, string idTipoRiesSelec)
        {
            HttpClient clientHttp = new HttpClient();
            clientHttp.BaseAddress = new Uri("https://localhost:44350/");

            var request = clientHttp.GetAsync("api/Poliza?IdPoliza=" + IdPoliza).Result;

            var requestTipoRiesgo = clientHttp.GetAsync("/api/TipoRiesgo").Result;

            if (requestTipoRiesgo.IsSuccessStatusCode)
            {
                var resulstring = requestTipoRiesgo.Content.ReadAsStringAsync().Result;
                var listadoRiesgo = JsonConvert.DeserializeObject<List<TipoRiesgo>>(resulstring);
                SelectList ListTipoRiesgo = new SelectList(listadoRiesgo, "IdRiesgo", "Nombre", Convert.ToInt32(idTipoRiesSelec));
                ViewBag.TipoRiesgo = ListTipoRiesgo;
            }

            var requestTipoPoliza = clientHttp.GetAsync("api/TipoPoliza").Result;


            if (requestTipoPoliza.IsSuccessStatusCode)
            {
                var resulstring = requestTipoPoliza.Content.ReadAsStringAsync().Result;
                var listadoPoliza = JsonConvert.DeserializeObject<List<TipoPoliza>>(resulstring);
                 SelectList ListCategories = new SelectList(listadoPoliza, "IdTipo", "Nombre", Convert.ToInt32(idTipoPolizSelec));
                ViewBag.TipoPoliza = ListCategories;
                //ViewBag.IdTipoPolizS = idTipoPolizSelec;
            }
          
            if (request.IsSuccessStatusCode)
            {
                var resulstring = request.Content.ReadAsStringAsync().Result;
                var resutado = JsonConvert.DeserializeObject<Poliza>(resulstring);
                return View(resutado);
            }
            

            return View();
        }

        [HttpPost]
        public ActionResult Actualizar(Poliza poliza)
        {
            HttpClient clientHttp = new HttpClient();
            clientHttp.BaseAddress = new Uri("https://localhost:44350/");
              //var request = clientHttp.GetAsync("api/Poliza?IdPoliza=" + IdPoliza).Result;
            var request = clientHttp.PutAsync("api/Poliza", poliza, new JsonMediaTypeFormatter()).Result;

            if (request.IsSuccessStatusCode)
            {
                var resulstring = request.Content.ReadAsStringAsync().Result;
                var resutado = JsonConvert.DeserializeObject<bool>(resulstring);


                if (resutado)
                {
                    return RedirectToAction("Index");
                }
                return View(poliza);
            }
            return View(poliza);
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            HttpClient clientHttp = new HttpClient();
            clientHttp.BaseAddress = new Uri("https://localhost:44350/");

            var request = clientHttp.DeleteAsync("api/Poliza?id=" + id).Result;

            if (request.IsSuccessStatusCode)
            {
                var resulstring = request.Content.ReadAsStringAsync().Result;
                var resutado = JsonConvert.DeserializeObject<bool>(resulstring);
                if (resutado)
                {
                    return RedirectToAction("Index");
                }

            }

            return View();
        }

        [HttpGet]
        public ActionResult Detalle(int idPoliza)
        {
            HttpClient clientHttp = new HttpClient();
            clientHttp.BaseAddress = new Uri("https://localhost:44350/");

            var request = clientHttp.GetAsync("api/Poliza?idPoliza=" + idPoliza).Result;

            if (request.IsSuccessStatusCode)
            {
                var resulstring = request.Content.ReadAsStringAsync().Result;
                var resutado = JsonConvert.DeserializeObject<Poliza>(resulstring);
                return View(resutado);
            }

            return View();
        }

      






    }
}

GAP.Seguros/GAP.Seguros/Views/Poliza/Actualizar.cshtml
@model GAP.Seguros.ModeloDatos.Poliza
@{
    ViewBag.Title = "Actualizar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Actualizar</h2>

<hr />

<form method="post" action="@Url.Action("Actualizar","Poliza")">
    <div class="form-group" style="visibility:hidden">
            @Html.TextBoxFor(x => x.IdPoliza, new { @class = "form-control" })
        </div>
    <div class="form-group">
        <label>Tipo de Póliza</label>
        @*@Html.DropDownList("TipoPoliza", new SelectList(ViewBag.TipoPoliza, "IdTipo", "Nombre"), new { @class = "form-control" })*@
        @*@Html.DropDownList("TipoPoliza", (SelectList)ViewBag.TipoPoliza)*@
        @Html.DropDownListFor(model => model.TipoPoliza, ViewBag.TipoPoliza as List<SelectListItem>, new { name = "TipoPoliza", id = "TipoPoliza", @class = "form-control" })
        @*@Html.DropDownList("TipoPoliza", new SelectList(ViewBag.TipoPoliza, "IdTipo", "Nombre"), new { @class = "form-control" })*@
        @* (model => model.TipoPoliza, (IEnumerable<SelectListItem>)ViewBag.TipoPoliza, new { @placeholder = "Seleccione un tipo de proyecto" })*@
        @* @Html.TextBoxFor(x => x.TipoPoliza, new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label>Póliza</label>
        @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Descripción</label>
        @Html.TextBoxFor(x => x.Descripcion, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Inicio</label>
        @Html.TextBoxFor(x => x.Inicio, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Duración</label>
        @Html.TextBoxFor(x => x.Duracion, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Precio</label>
        @Html.TextBoxFor(x => x.Precio, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Tipo de Riesgo</label>
        @Html.DropDownListFor(model => model.TipoRiesgo, ViewBag.TipoRiesgo as List<SelectListItem>, new { name = "TipoRiesgo", id = "TipoRiesgo", @class = "form-control" })
        @*@Html.DropDownList("TipoRiesgo", new SelectList(ViewBag.TipoRiesgo, "IdRiesgo", "Nombre"), new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label>Activo</label>
        @Html.CheckBoxFor(model => model.Activo)

        @*@Html.TextBoxFor(x => x.Activo, new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label>Usuario Creación</label>
        @Html.TextBoxFor(x => x.UsuarioCreacion, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Fecha Creación</label>
        @Html.TextBoxFor(x => x.FechaCreacion, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" class="btn-success" value="Enviar" />
        <a href="@Url.Action("Index", "Poliza")" class="btn btn-info riht">Regresar</a>
    </div>


</form>

GAP.Seguros/GAP.Seguros/Views/Poliza/Detalle.cshtml
@model GAP.Seguros.ModeloDatos.Poliza
@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalle Poliza</h2>
<hr />

<div class="form-group">
    <label class="label label-info">Número de Póliza</label>
    <b> @Model.IdPoliza </b>
</div>
<div class="form-group">
    <label class="label label-info">Tipo de Poliza</label>
    @*<b> @Model.TipoPoliza </b>*@
    @{
        switch (@Model.IdPoliza)
        {
            case 1:
                // Use the text block below to separate html elements from code
                <text>
                    <b>Terremoto</b>
                </text>
                break;  // Always break each case
            case 2:
                <text>
                     <b>Incendio</b>
                </text>
                break;
            case 3:
                <text>
                    <b>Robo</b>
                </text>
                break;
            default:
                <text>
                    <b>Perdida</b>
                </text>
                break;
        }
    }
</div>
<div class="form-group">
    <label class="label label-info">Nombre Póliza</label>
    <b> @Model.Nombre </b>
</div>
<div class="form-group">
    <label class="label label-info">Descripción</label>
    <b> @Model.Descripcion </b>
</div>
<div class="form-group">
    <label class="label label-info">Fecha Inicio</label>
    <b> @Model.Inicio </b>
</div>
<div class="form-group">
    <label class="label label-info">Duración</label>
    <b>  @Model.Duracion  </b> <b> meses</b>
</div>
<div class="form-group">
    <label class="label label-info">Precio</label>
    <b>  @Model.Precio </b>
</div>
<div class="form-group">
    <label class="label label-info">Tipo de Riesgo</label>
    @{
        switch (@Model.TipoRiesgo)
        {
            case "1":
                // Use the text block below to separate html elements from code
                <text>
                    <b>Alto</b>
                </text>
                break;  // Always break each case
            case "2":
                <text>
                    <b>Medio-Alto</b>
                </text>
                break;
            case "3":
                <text>
                    <b>Medio</b>
                </text>
                break;
            default:
                <text>
                    <b>Bajo</b>
                </text>
                break;
        }
    }
    @*<b>  @Model.TipoRiesgo </b>*@
</div>
<div class="form-group">
    <label class="label label-info">Estado</label>
    @if (@Model.Activo)
    {
        <b> Activo</b>
    }
    else
    {
       <b> Inactivo </b>
    }

</div>
<div class="form-group">
    <label class="label label-info">Usuario Creación</label>
    <b>    @Model.UsuarioCreacion </b>
</div>
<div class="form-group">
    <label class="label label-info">Fecha Creación</label>
    <b>   @Model.FechaCreacion </b>
</div>
<div class="form-group">
    <a href="@Url.Action("Index", "Poliza")" class="btn btn-info riht">Regresar</a>
</div>

GAP.Seguros/GAP.Seguros/Views/Poliza/Index.cshtml
@model List<GAP.Seguros.ModeloDatos.Poliza>
@{
    ViewBag.Title = "Poliza";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>
    <a href="@Url.Action("Nuevo", "Poliza")" class="btn btn-primary right">Nuevo</a>
    Listado de Polizas</h2>
    <Table class="table table-striped">
    <thead >
        <tr >
            <td >Número</td>
            <td>Tipo Póliza</td>
            <td>Inicio</td>
            @*<td>Duracion</td>
            <td>Precio</td>
            <td>IdTipoRiesgo</td>
            <td>Activo</td>*@
            <td>Usuario Creacion</td>
            <td>Fecha Creacion</td>
            <td>Accciones</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var poliza in Model)
        {
        <tr>
            <th scope="row">@poliza.IdPoliza</th>
           
            @{
                switch (@poliza.TipoPoliza)
                {
                    case "1":
                        // Use the text block below to separate html elements from code
                        <text>
                            <th scope="row">Terremoto</th>
                        </text>
                        break;  // Always break each case
                    case "2":
                        <text>
                            <th scope="row">Incendio</th>
                        </text>
                        break;
                    case "3":
                        <text>
                            <th scope="row">Robo</th>
                        </text>
                        break;
                    default:
                        <text>
                            <th scope="row">Perdida</th>
                        </text>
                        break;
                }
            }
            @*<td>@poliza.TipoPoliza</td>*@
            <td>@poliza.Inicio</td>
            @*<td>@poliza.Duracion</td>
        <td>@poliza.Precio</td>
        <td>@poliza.IdTipoRiesgo</td>
        <td>@poliza.Activo</td>*@
            <td>@poliza.UsuarioCreacion</td>
            <td>@poliza.FechaCreacion</td>
            <td>
                <a href="@Url.Action("Actualizar", "Poliza", new { idPoliza = poliza.IdPoliza, idTipoPolizSelec = poliza.TipoPoliza, idTipoRiesSelec = poliza.TipoRiesgo})" class="btn btn-success">Actualizar</a>
                <a href="@Url.Action("Eliminar", "Poliza", new { id = poliza.IdPoliza})" class="btn btn-danger">Eliminar</a>
                <a href="@Url.Action("Detalle", "Poliza", new { idPoliza = poliza.IdPoliza})" class="btn btn-info riht">Ver Detalle</a>
            </td>
        </tr>
        }

    </tbody>
</Table>

GAP.Seguros/GAP.Seguros/Views/Poliza/Nuevo.cshtml
@model GAP.Seguros.ModeloDatos.Poliza
@{
    ViewBag.Title = "Nuevo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Nueva Póliza</h2>
<hr />

<form method="post" action="@Url.Action("Nuevo", "Poliza")">
    @*<div class="form-group">
        <label>IdPoliza</label>
        @Html.TextBoxFor(x => x.IdPoliza, new { @class = "form-control" })
    </div>*@
    <div class="form-group">
        <label>Tipo de Póliza</label>
        @Html.DropDownList("TipoPoliza", new SelectList(ViewBag.TipoPoliza, "IdTipo", "Nombre"), new { @class = "form-control" })
           @* (model => model.TipoPoliza, (IEnumerable<SelectListItem>)ViewBag.TipoPoliza, new { @placeholder = "Seleccione un tipo de proyecto" })*@
       @* @Html.TextBoxFor(x => x.TipoPoliza, new { @class = "form-control" })*@
    </div>
    <div class="form-group">
        <label>Póliza</label>
        @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Descripción</label>
        @Html.TextBoxFor(x => x.Descripcion, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Inicio</label>
        @Html.TextBoxFor(x => x.Inicio, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Duración</label>
        @Html.TextBoxFor(x => x.Duracion, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Precio</label>
        @Html.TextBoxFor(x => x.Precio, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Tipo de Riesgo</label>
        @Html.DropDownList("TipoRiesgo", new SelectList(ViewBag.TipoRiesgo, "IdRiesgo", "Nombre"), new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Activo</label>
        @Html.TextBoxFor(x => x.Activo, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Usuario Creación</label>
        @Html.TextBoxFor(x => x.UsuarioCreacion, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Fecha Creación</label>
        @Html.TextBoxFor(x => x.FechaCreacion, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" class="btn-success" value="Enviar" />
        <a href="@Url.Action("Index", "Poliza")" class="btn btn-info riht">Regresar</a>
    </div>


</form>